export const businessGroupFields = [
  'BusinessName',
  'BusinessType',
  'HoursDaysOfOperationDescription',
  'HoursDaysOfOperation',
  'LaborInformation',
  'LeaseAmount',
  'LeaseAmountFrequency',
  'LeaseAssignableYN',
  'LeaseExpiration',
  'LeaseRenewalOptionYN',
  'NumberOfFullTimeEmployees',
  'NumberOfPartTimeEmployees',
  'OwnershipType',
  'SeatingCapacity',
  'SpecialLicenses',
  'YearEstablished',
  'YearsCurrentOwner',
] as const
