export const characteristicGroupFields = [
  'AnchorsCoTenants',
  'AvailableLeaseType',
  'CommunityFeatures',
  'CurrentUse',
  'DevelopmentStatus',
  'Fencing',
  'FrontageLength',
  'FrontageType',
  'Furnished',
  'HorseAmenities',
  'HorseYN',
  'LandLeaseAmount',
  'LandLeaseAmountFrequency',
  'LandLeaseExpirationDate',
  'LandLeaseYN',
  'LaundryFeatures',
  'LeaseTerm',
  'LotDimensionsSource',
] as const
