const ListingData = attributes({
  Id: Number,
  ImportConfigId: Number,
  DisplayAsSold: Number,
  ListingKey: String,
  ListingKeyNumeric: Number,
  ListingId: String,
  StandardStatus: String,
  MlsStatus: String,
  ListingService: String,
  ListingAgreement: String,
  ListAOR: String,
  LeaseConsideredYN: String,
  HomeWarrantyYN: String,
  ClosePrice: Number,
  ListPrice: Number,
  OriginalListPrice: Number,
  PreviousListPrice: Number,
  DaysOnMarket: Number,
  CloseDate: Date,
  OriginatingSystemID: String,
  OriginatingSystemKey: String,
  OriginatingSystemName: String,
  SourceSystemID: String,
  SourceSystemKey: String,
  SourceSystemName: String,
  ModificationTimestamp: Date,
  OriginalEntryTimestamp: Date,
  PhotosChangeTimestamp: Date,
  DatesGroup: JSON,
  ClosingGroup: JSON,
  CompensationGroup: JSON,
  MediaGroup: JSON,
  ShowingGroup: JSON,
  RemarksGroup: JSON,
})(class ListingData {});

module.exports = ListingData;
