export const taxGroupFields = [
  'AdditionalParcelsDescription',
  'AdditionalParcelsYN',
  'ParcelNumber',
  'PublicSurveyRange',
  'PublicSurveySection',
  'PublicSurveyTownship',
  'TaxAnnualAmount',
  'TaxAssessedValue',
  'TaxBlock',
  'TaxBookNumber',
  'TaxLegalDescription',
  'TaxLot',
  'TaxMapNumber',
  'TaxOtherAnnualAssessmentAmount',
  'TaxParcelLetter',
  'TaxStatusCurrent',
  'TaxTract',
  'TaxYear',
  'ZoningDescription',
  'Zoning',
] as const
